#
#   ____ _           _  _____      ____                                          _
#  / ___| |__   __ _| ||_   _|__  / ___|___  _ __ ___  _ __ ___   __ _ _ __   __| |
# | |   | '_ \ / _` | __|| |/ _ \| |   / _ \| '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` |
# | |___| | | | (_| | |_ | | (_) | |__| (_) | | | | | | | | | | | (_| | | | | (_| |
#  \____|_| |_|\__,_|\__||_|\___/ \____\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|
#
#                  Main configuration (version ${project.version})
#

# Whether you want all triggering commands to be logged (true)
log: true

# Whether you want the chat message itself to be cancelled (true)
cancel-chat: true

# Whether you want to allow the chat message to process if the user does not have permission.
allow-chat-with-no-permissions: true

# Whether you want to allow the chat message to process if the user is in the incorrect world.
allow-chat-with-incorrect-world: true
